import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({
  baseDirectory: dirname(fileURLToPath(import.meta.url)),
});

const config = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // next-env.d.ts is generated by Next.js and is not ours to lint.
    ignores: [".next/**", "node_modules/**", "scripts/**", "next-env.d.ts", ".qa-shots/**"],
  },
];

export default config;
